[package]
name = "ci-transfer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.0", features = ["derive"] }
ssh2 = "0.9"
openssl = { version = "=0.10.33", features = ["vendored"] }